platform :ios, '7.0'

source 'https://github.com/gloryFlow/FBBRepositories.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'FBBMain' do

    # 私有仓库
    pod 'FBBUserCenter'
    pod 'FBBHttpClient'

    # 第三方库
    pod 'Masonry'
    pod 'SDWebImage'
    pod 'MGJRouter'

end
